server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/counting?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    com.qianluohan.basic.dao: debug
mybatis:
  mapper-locations: classpath*:./mapper/*.xml
  type-aliases-package: com/qianluohan/basic/dao

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0